version: '3.1'

volumes:
  images:

networks:
  mynetwork:
    driver: bridge

services:
  backend:
    env_file:
      - frontend/.env
    restart: unless-stopped 
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
    networks:
      - mynetwork
    volumes:
      - ./static:/static
      - images:/backend/media/images

  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mynetwork
    env_file:
      - frontend/.env
    volumes:
      - images:/frontend/public/media/images

  nginx:
      image: nginx:alpine
      restart: unless-stopped
      ports:
        - "80:80"
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
        - ./static:/static
        - images:/backend/media/images
      networks:
        - mynetwork
      depends_on:
        - frontend
        - backend