# Generated by Django 4.2.4 on 2023-09-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_image_image_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='newtab',
            field=models.BooleanField(default=True, verbose_name='Open in new Tab'),
        ),
    ]
