# Generated by Django 4.2.4 on 2024-11-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_social'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social',
            options={'ordering': ('order',)},
        ),
        migrations.RemoveField(
            model_name='social',
            name='threads',
        ),
        migrations.AlterField(
            model_name='social',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
