# Generated by Django 4.2.4 on 2023-09-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_menuitem_newtab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='newtab',
            field=models.BooleanField(default=False, verbose_name='Open in new Tab'),
        ),
    ]
