# Generated by Django 4.2.4 on 2024-11-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_social_options_remove_social_threads_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='lang',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('tr', 'Turkish')], default='en', max_length=7, unique=True, verbose_name='Language'),
        ),
        migrations.AlterUniqueTogether(
            name='homepage',
            unique_together={('lang',)},
        ),
    ]
