# Generated by Django 4.2.4 on 2024-11-15 16:22

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_homepage_lang_alter_homepage_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=django_summernote.fields.SummernoteTextField(verbose_name='Page Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_summernote.fields.SummernoteTextField(verbose_name='Post Content'),
        ),
    ]
