# Generated by Django 4.2.4 on 2023-09-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_menuitem_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='lang',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('tr', 'Turkish')], default='en', max_length=2, verbose_name='Language'),
        ),
    ]
