# Generated by Django 4.2.4 on 2023-09-25 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_menuitem_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='menu',
        ),
    ]
