# Generated by Django 4.2.4 on 2023-10-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_page_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='page',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='lang',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('tr', 'Turkish')], default='en', max_length=7, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='lang',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('tr', 'Turkish')], default='en', max_length=7, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='page',
            name='lang',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('tr', 'Turkish')], default='en', max_length=7, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='post',
            name='lang',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('tr', 'Turkish')], default='en', max_length=7, verbose_name='Language'),
        ),
    ]
