# Generated by Django 4.2.4 on 2023-10-30 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_page_options_alter_post_options_page_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.image')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.post')),
            ],
        ),
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.image')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.page')),
            ],
        ),
        migrations.AlterField(
            model_name='page',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='page_images', through='content.PageImage', to='content.image', verbose_name='Select Content Images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='post_images', through='content.PostImage', to='content.image', verbose_name='Select Content Images'),
        ),
    ]
